Upgrade to `@babel/*-rc.2.
This resolves a frustrating error I encountered where I was receiving:

    ReferenceError: Unknown option: .caller

...when trying to use `@babel/register`.  This mysteriously went away when I
upgraded to `rc.2`, which was inspired after I honed in on related work to
the `caller` option in https://github.com/babel/babel/pull/8485 after debugging
Babel's `loadOptions` (in `7.0.0-rc.1`) with the Node.js debugger.